SELECT
-- STORE
STORE.STORE_RHID, STORE.EFFECTIVE_START_DATETIME AS STORE_EFFECTIVE_START_DATETIME, STORE.EFFECTIVE_END_DATETIME AS STORE_EFFECTIVE_END_DATETIME,
STORE.STORE_CODE, STORE.STORE_NAME, STORE.SKX_STORE_CODE, STORE.SKX_STORE_NAME,STORE.GEO_LOCATION_RHID,STORE.TIME_ZONE_RHID,
STORE.CLIMATE_REGION_RHID, STORE.REGION_RHID, STORE.LOCATION_TYPE_RHID, STORE.STORE_TYPE_RHID, STORE.RETAIL_DISTRICT_RHID, STORE.RETAIL_REGION_RHID,
STORE.RETAIL_TERRITORY_RHID, STORE.DISTRIBUTION_CENTER_RHID, STORE.CUSTOMER_RHID, STORE.OWNERSHIP_TYPE_RHID, STORE.CUSTOMER_TYPE_RHID, STORE.SUBOFFICE_RHID,
STORE.COMPANY_RHID, STORE.STORE_DESIGN_RHID, STORE.RETAIL_BRAND_RHID, STORE.STORE_DISCOUNT_TYPE_RHID, STORE.STORE_PRODUCT_MIX_RHID, STORE.RETAIL_VENUE_RHID,
STORE.STORE_DATA_AGGREGATION_RHID, STORE.STORE_LOCATION_GROUP_RHID, STORE.STORE_BUY_GROUP_RHID, STORE.LOCATION_TIER_RHID, STORE.STORE_PHONE_NBR,
STORE.STORE_CONTACT_NAME, STORE.STATUS_CODE, STORE.ACTIVE_FLAG,
-- ADDRESS
ADDR.ADDRESS_RHID, ADDR.EFFECTIVE_START_DATETIME AS ADDR_EFFECTIVE_START_DATETIME, ADDR.EFFECTIVE_END_DATETIME AS ADDR_EFFECTIVE_END_DATETIME,
ADDR.CITY_NAME, ADDR.STATE_NAME, ADDR.STATE_CODE,
-- STORE_TYPE
STORE_TYPE.EFFECTIVE_START_DATETIME AS STORE_TYPE_EFFECTIVE_START_DATETIME, STORE_TYPE.EFFECTIVE_END_DATETIME AS STORE_TYPE_EFFECTIVE_END_DATETIME,
STORE_TYPE.STORE_TYPE_CODE, STORE_TYPE.STORE_SUBTYPE_CODE, STORE_TYPE.STORE_TYPE_DESC, STORE_TYPE.STORE_SUBTYPE_DESC,
-- LOCATION_TYPE
LOCATION_TYPE.EFFECTIVE_START_DATETIME AS LOCATION_TYPE_EFFECTIVE_START_DATETIME, LOCATION_TYPE.EFFECTIVE_END_DATETIME AS LOCATION_TYPE_EFFECTIVE_END_DATETIME,
LOCATION_TYPE.LOCATION_TYPE_CODE, LOCATION_TYPE.LOCATION_TYPE_DESC,
-- OWNERSHIP_TYPE
OWNERSHIP_TYPE.EFFECTIVE_START_DATETIME AS OWNERSHIP_TYPE_EFFECTIVE_START_DATETIME, OWNERSHIP_TYPE.EFFECTIVE_END_DATETIME AS OWNERSHIP_TYPE_EFFECTIVE_END_DATETIME,
OWNERSHIP_TYPE.OWNERSHIP_TYPE_CODE, OWNERSHIP_TYPE.OWNERSHIP_TYPE_DESC,
-- RETAIL_DISTRICT
RETAIL_DISTRICT.EFFECTIVE_START_DATETIME AS RETAIL_DISTRICT_EFFECTIVE_START_DATETIME,RETAIL_DISTRICT.EFFECTIVE_END_DATETIME AS RETAIL_DISTRICT_EFFECTIVE_END_DATETIME,
RETAIL_DISTRICT.RETAIL_DISTRICT_CODE,RETAIL_DISTRICT.RETAIL_DISTRICT_NAME,
-- RETAIL_REGION
RETAIL_REGION.EFFECTIVE_START_DATETIME AS RETAIL_REGION_EFFECTIVE_START_DATETIME,
RETAIL_REGION.EFFECTIVE_END_DATETIME AS RETAIL_REGION_EFFECTIVE_END_DATETIME,
RETAIL_REGION.RETAIL_REGION_CODE, RETAIL_REGION.RETAIL_REGION_NAME,
-- RETAIL_TERRITORY
RETAIL_TERRITORY.EFFECTIVE_START_DATETIME AS RETAIL_TERRITORY_EFFECTIVE_START_DATETIME,
RETAIL_TERRITORY.EFFECTIVE_END_DATETIME AS RETAIL_TERRITORY_EFFECTIVE_END_DATETIME,
RETAIL_TERRITORY.RETAIL_TERRITORY_CODE, RETAIL_TERRITORY.RETAIL_TERRITORY_NAME,
-- DISTRIBUTION_CENTER
DISTRIBUTION_CENTER.EFFECTIVE_START_DATETIME AS DIST_CENTER_EFFECTIVE_START_DATETIME,
DISTRIBUTION_CENTER.EFFECTIVE_END_DATETIME AS DIST_CENTER_EFFECTIVE_END_DATETIME,
DISTRIBUTION_CENTER.DISTRIBUTION_CENTER_CODE, DISTRIBUTION_CENTER.DISTRIBUTION_CENTER_NAME,
DISTRIBUTION_CENTER.COMPANY_RHID, DISTRIBUTION_CENTER.CUSTOMER_RHID, DISTRIBUTION_CENTER.ADDRESS_RHID,
DISTRIBUTION_CENTER.DISTRIBUTION_CENTER_TYPE_CODE, DISTRIBUTION_CENTER.DISTRIBUTION_CENTER_TYPE_DESC,
-- CUSTOMER
CUSTOMER.EFFECTIVE_START_DATETIME AS CUST_EFFECTIVE_START_DATETIME,
CUSTOMER.EFFECTIVE_END_DATETIME AS CUST_EFFECTIVE_END_DATETIME,
CUSTOMER.CUSTOMER_CODE, CUSTOMER.CUSTOMER_NAME, CUSTOMER.PARENT_CUSTOMER_RHID,
CUSTOMER.COMPANY_RHID, CUSTOMER.SUBOFFICE_RHID, CUSTOMER.CUSTOMER_TYPE_RHID,
CUSTOMER.ADDRESS_RHID, CUSTOMER.LANGUAGE_RHID, CUSTOMER.REGION_RHID,
CUSTOMER.CONTACT_NAME, CUSTOMER.CURRENCY_RHID,
-- CUSTOMER_TYPE
CUSTOMER_TYPE.EFFECTIVE_START_DATETIME AS CUST_TYPE_EFFECTIVE_START_DATETIME,
CUSTOMER_TYPE.EFFECTIVE_END_DATETIME AS CUST_TYPE_EFFECTIVE_END_DATETIME,
CUSTOMER_TYPE.COMPANY_RHID, CUSTOMER_TYPE.CUSTOMER_TYPE_CODE, CUSTOMER_TYPE.CUSTOMER_TYPE_DESC,
-- SUBOFFICE
SUBOFFICE.EFFECTIVE_START_DATETIME AS SUBOFFICE_EFFECTIVE_START_DATETIME,
SUBOFFICE.EFFECTIVE_END_DATETIME AS SUBOFFICE_EFFECTIVE_END_DATETIME,
SUBOFFICE.SUBOFFICE_CODE, SUBOFFICE.SUBOFFICE_NAME,
-- COMPANY
COMPANY.EFFECTIVE_START_DATETIME AS COMPANY_EFFECTIVE_START_DATETIME,
COMPANY.EFFECTIVE_END_DATETIME AS COMPANY_EFFECTIVE_END_DATETIME,
COMPANY.COMPANY_CODE, COMPANY.COMPANY_NAME,
-- TIMEZONE
TIMEZONE.EFFECTIVE_START_DATETIME AS TIMEZONE_EFFECTIVE_START_DATETIME,
TIMEZONE.EFFECTIVE_END_DATETIME AS TIMEZONE_EFFECTIVE_END_DATETIME,
TIMEZONE.TIME_ZONE_CODE, TIMEZONE.TIME_ZONE_DESC, TIMEZONE.DAYLIGHT_SAVINGS_IND,
TIMEZONE.STD_OFFSET_FROM_UTC_TEXT, TIMEZONE.STD_OFFSET_IN_MIN_NBR,
TIMEZONE.DAYLIGHT_OFFSET_FROM_UTC_TEXT, TIMEZONE.DAYLIGHT_OFFSET_IN_MIN_NBR,
-- CLIMATE_REGION
CLIMATE_REGION.EFFECTIVE_START_DATETIME AS CLIMATE_REG_EFFECTIVE_START_DATETIME,
CLIMATE_REGION.EFFECTIVE_END_DATETIME AS CLIMATE_REG_EFFECTIVE_END_DATETIME,
CLIMATE_REGION.CLIMATE_REGION_CODE, CLIMATE_REGION.CLIMATE_REGION_DESC,
-- GEO_LOCATION
GEO_LOCATION.EFFECTIVE_START_DATETIME AS GEO_LOC_EFFECTIVE_START_DATETIME,
GEO_LOCATION.EFFECTIVE_END_DATETIME AS GEO_LOC_EFFECTIVE_END_DATETIME,
GEO_LOCATION.GEO_LOCATION_CODE, GEO_LOCATION.GEO_LOCATION_DESC,
-- CURRENCY
CURRENCY.EFFECTIVE_START_DATETIME AS CURR_EFFECTIVE_START_DATETIME,
CURRENCY.EFFECTIVE_END_DATETIME AS CURR_EFFECTIVE_END_DATETIME,
CURRENCY.CURRENCY_NAME,
-- REGION
REGION.EFFECTIVE_START_DATETIME AS REG_EFFECTIVE_START_DATETIME,
REGION.EFFECTIVE_END_DATETIME AS REG_EFFECTIVE_END_DATETIME,
REGION.REGION_CODE, REGION.REGION_NAME

FROM "DB_REF_HUB"."REF_HUB"."MST_STORE" STORE
LEFT JOIN "DB_REF_HUB"."REF_HUB"."MST_ADDRESS" ADDR
ON STORE.GEO_LOCATION_RHID = ADDR.ADDRESS_RHID
LEFT JOIN "DB_REF_HUB"."REF_HUB"."REF_STORE_TYPE" STORE_TYPE
ON STORE.STORE_TYPE_RHID = STORE_TYPE.STORE_TYPE_RHID
LEFT JOIN "DB_REF_HUB"."REF_HUB"."REF_LOCATION_TYPE" LOCATION_TYPE
ON STORE.LOCATION_TYPE_RHID = LOCATION_TYPE.LOCATION_TYPE_RHID
LEFT JOIN "DB_REF_HUB"."REF_HUB"."REF_OWNERSHIP_TYPE" OWNERSHIP_TYPE
ON STORE.OWNERSHIP_TYPE_RHID = OWNERSHIP_TYPE.OWNERSHIP_TYPE_RHID
LEFT JOIN "DB_REF_HUB"."REF_HUB"."REF_RETAIL_DISTRICT" RETAIL_DISTRICT
ON STORE.RETAIL_DISTRICT_RHID = RETAIL_DISTRICT.RETAIL_DISTRICT_RHID
LEFT JOIN "DB_REF_HUB"."REF_HUB"."REF_RETAIL_REGION" RETAIL_REGION
ON STORE.RETAIL_REGION_RHID = RETAIL_REGION.RETAIL_REGION_RHID
LEFT JOIN "DB_REF_HUB"."REF_HUB"."REF_RETAIL_TERRITORY" RETAIL_TERRITORY
ON STORE.RETAIL_TERRITORY_RHID = RETAIL_TERRITORY.RETAIL_TERRITORY_RHID
LEFT JOIN "DB_REF_HUB"."REF_HUB"."MST_DISTRIBUTION_CENTER" DISTRIBUTION_CENTER
ON STORE.DISTRIBUTION_CENTER_RHID = DISTRIBUTION_CENTER.DISTRIBUTION_CENTER_RHID
LEFT JOIN "DB_REF_HUB"."REF_HUB"."MST_CUSTOMER" CUSTOMER
ON STORE.CUSTOMER_RHID = CUSTOMER.CUSTOMER_RHID
LEFT JOIN "DB_REF_HUB"."REF_HUB"."REF_CUSTOMER_TYPE" CUSTOMER_TYPE
ON STORE.CUSTOMER_TYPE_RHID = CUSTOMER_TYPE.CUSTOMER_TYPE_RHID
LEFT JOIN "DB_REF_HUB"."REF_HUB"."MST_SUBOFFICE" SUBOFFICE
ON STORE.SUBOFFICE_RHID = SUBOFFICE.SUBOFFICE_RHID
LEFT JOIN "DB_REF_HUB"."REF_HUB"."MST_COMPANY" COMPANY
ON STORE.COMPANY_RHID = COMPANY.COMPANY_RHID
LEFT JOIN "DB_REF_HUB"."REF_HUB"."MST_TIMEZONE" TIMEZONE
ON STORE.TIME_ZONE_RHID = TIMEZONE.TIME_ZONE_RHID
LEFT JOIN "DB_REF_HUB"."REF_HUB"."REF_CLIMATE_REGION" CLIMATE_REGION
ON STORE.CLIMATE_REGION_RHID = CLIMATE_REGION.CLIMATE_REGION_RHID
LEFT JOIN "DB_REF_HUB"."REF_HUB"."REF_GEO_LOCATION" GEO_LOCATION
ON STORE.GEO_LOCATION_RHID = GEO_LOCATION.GEO_LOCATION_RHID
LEFT JOIN "DB_REF_HUB"."REF_HUB"."MST_CURRENCY" CURRENCY
ON CUSTOMER.CURRENCY_RHID = CURRENCY.CURRENCY_RHID
LEFT JOIN "DB_REF_HUB"."REF_HUB"."REF_REGION" REGION
ON STORE.REGION_RHID = REGION.REGION_RHID


