-------CHANGE S3 Paths to Production paths****************----------

-------CHANGE S3 Paths to Production paths****************----------

------ Create Database------------
CREATE DATABASE TRANSIENT_DL
CREATE DATABASE SLV_RETAIL_SALES
CREATE DATABASE GLD_PERFORMANCE

------ Create USECASE AUDIT TABLES Tables-------------------

CREATE TABLE IF NOT EXISTS DELTA_LOGS.USECASE_AUDIT_LOGS 
(
  JOBNAME STRING,
  SRC_LAST_UPD_TIMESTAMP TIMESTAMP,
  LOAD_STATUS STRING,
  REC_CREATE_TIMESTAMP TIMESTAMP,
  REC_CREATE_USER_NAME STRING,
  REC_UPDATE_TIMESTAMP TIMESTAMP,
  REC_UPDATE_USER_NAME STRING
) 
USING DELTA 
LOCATION 's3://skx-dataeng-datalake/audit/usecase_audit_logs' 
TBLPROPERTIES ('layer' = 'SILVER');

------ Create SILVER Tables-------------------

CREATE TABLE SLV_RETAIL_SALES.AGG_STORE_VISITS_DAILY
(
VISIT_DATE_KEY INTEGER,
STORE_RHID INTEGER,
STORE_GRPID STRING,
VISIT_DATE DATE,
ENTRY_COUNT INTEGER,
EXIT_COUNT INTEGER,
REC_CREATE_TIMESTAMP TIMESTAMP,
REC_CREATE_USER_NAME STRING,
REC_UPDATE_TIMESTAMP TIMESTAMP,
REC_UPDATE_USER_NAME STRING,
REC_CREATE_DATE_KEY INTEGER,
REC_CREATE_TIME_KEY INTEGER
)
USING DELTA
PARTITIONED BY (VISIT_DATE_KEY)
LOCATION 's3://skx-dataeng-datalake/integrated/slv_retail_sales/agg_store_visits_daily'
TBLPROPERTIES ('layer'='SILVER')

------

CREATE TABLE SLV_RETAIL_SALES.DTL_RETAIL_SALES 
(
  ORDER_ID INTEGER,
  ORDER_ITEM_ID INTEGER,
  ORDER_STATUS_CODE STRING,
  ORDER_CHANNEL_CODE STRING,
  TRANSACTION_TYPE_CODE STRING,
  ORDER_TIMESTAMP TIMESTAMP,
  ORDER_DATE_KEY INTEGER,
  COLOR_RHID INTEGER,
  COLOR_GRPID STRING,
  PRODUCT_RHID INTEGER,
  PRODUCT_GRPID STRING,
  SIZE_RHID INTEGER,
  SIZE_GRPID STRING,
  STYLE_RHID INTEGER,
  STYLE_GRPID STRING,
  DIVISION_RHID INTEGER,
  DIVISION_GRPID STRING,
  CATALOG_ITEM_CODE STRING,
  STORE_RHID INTEGER,
  STORE_GRPID STRING,
  SHIP_STORE_RHID INTEGER,
  SHIP_STORE_GRPID STRING,
  ITEM_TYPE_DESC STRING,
  UNIT_PRICE_AMT DECIMAL(20, 6),
  SALES_QTY INTEGER,
  TAX_TYPE1_CODE STRING,
  TAX_TYPE1_AMT DECIMAL(20, 6),
  TAX_TYPE2_CODE STRING,
  TAX_TYPE2_AMT DECIMAL(20, 6),
  TAX_TYPE3_CODE STRING,
  TAX_TYPE3_AMT DECIMAL(20, 6),
  TAX_TYPE4_CODE STRING,
  TAX_TYPE4_AMT DECIMAL(20, 6),
  DISCOUNT1_REASON_CODE STRING,
  CANCEL_DATE DATE,
  RETURN_DATE DATE,
  VERSION_NBR INTEGER,
  CARRIER_NAME STRING,
  SHIPPING_VENDOR_NAME STRING,
  TRACKING_CODE STRING,
  CHARGE_IND INTEGER,
  PICK_CODE STRING,
  AVAILABLE_DATE DATE,
  PICK_DATE DATE,
  EMAIL_NOTIFIED_IND INTEGER,
  ORDER_FAILED_NOTIFIED_IND INTEGER,
  ORDER_FAILED_NOTIFIED_DATE DATE,
  ORDER_NOTES_TEXT STRING,
  REVIEW_NOTIFIED_IND INTEGER,
  CREDITED_IND INTEGER,
  COMMENTS_TEXT STRING,
  SHIPPING_METHOD_CODE STRING,
  SHIP_DATE DATE,
  CHARGE_TIMESTAMP TIMESTAMP,
  CURRENCY_RHID INTEGER,
  CURRENCY_GRPID STRING,
  REC_CREATE_TIMESTAMP TIMESTAMP,
  REC_CREATE_USER_NAME STRING,
  REC_UPDATE_TIMESTAMP TIMESTAMP,
  REC_UPDATE_USER_NAME STRING,
  REC_CREATE_DATE_KEY INTEGER,
  REC_CREATE_TIME_KEY INTEGER
)
USING DELTA 
PARTITIONED BY (REC_CREATE_DATE_KEY) 
LOCATION 's3://skx-dataeng-datalake/integrated/slv_retail_sales/dtl_retail_sales' 
TBLPROPERTIES ('layer'='SILVER')

------ Create GOLD Tables-------------------

CREATE TABLE GLD_PERFORMANCE.AGG_STORE_METRICS_DAILY 
(
  DATE_KEY INTEGER,
  STORE_RHID INTEGER,
  LATEST_OPEN_DATE DATE,
  LATEST_CLOSE_DATE DATE,
  TOTAL_VISIT_COUNT INTEGER,
  TOTAL_TRANSACTION_COUNT INTEGER,
  TOTAL_SALES_QUANTITY INTEGER,
  TOTAL_RETURN_QUANTITY INTEGER,
  TOTAL_SALES_USD_AMOUNT DECIMAL(20, 6),
  TOTAL_TAX_USD_AMOUNT DECIMAL(20, 6),
  TOTAL_DISCOUNT_USD_AMOUNT DECIMAL(20, 6),
  TOTAL_PROMO_USD_AMOUNT DECIMAL(20, 6),
  TOTAL_SHIPPING_USD_AMOUNT DECIMAL(20, 6),
  FOOTWEAR_TRANSACTION_COUNT INTEGER,
  FOOTWEAR_SALES_QUANTITY INTEGER,
  FOOTWEAR_RETURN_QUANTITY INTEGER,
  FOOTWEAR_SALES_USD_AMOUNT DECIMAL(20, 6),
  FOOTWEAR_TAX_USD_AMOUNT DECIMAL(20, 6),
  FOOTWEAR_DISCOUNT_USD_AMOUNT DECIMAL(20, 6),
  FOOTWEAR_PROMO_USD_AMOUNT DECIMAL(20, 6),
  FOOTWEAR_SHIPPING_USD_AMOUNT DECIMAL(20, 6),
  APPAREL_TRANSACTION_COUNT INTEGER,
  APPAREL_SALES_QUANTITY INTEGER,
  APPAREL_RETURN_QUANTITY INTEGER,
  APPAREL_SALES_USD_AMOUNT DECIMAL(20, 6),
  APPAREL_TAX_USD_AMOUNT DECIMAL(20, 6),
  APPAREL_DISCOUNT_USD_AMOUNT DECIMAL(20, 6),
  APPAREL_PROMO_USD_AMOUNT DECIMAL(20, 6),
  APPAREL_SHIPPING_USD_AMOUNT DECIMAL(20, 6),
  ACCESSORIES_TRANSACTION_COUNT INTEGER,
  ACCESSORIES_SALES_QUANTITY INTEGER,
  ACCESSORIES_RETURN_QUANTITY INTEGER,
  ACCESSORIES_SALES_USD_AMOUNT DECIMAL(20, 6),
  ACCESSORIES_TAX_USD_AMOUNT DECIMAL(20, 6),
  ACCESSORIES_DISCOUNT_USD_AMOUNT DECIMAL(20, 6),
  ACCESSORIES_PROMO_USD_AMOUNT DECIMAL(20, 6),
  ACCESSORIES_SHIPPING_USD_AMOUNT DECIMAL(20, 6),
  REC_CREATE_TIMESTAMP TIMESTAMP,
  REC_CREATE_USER_NAME STRING,
  REC_UPDATE_TIMESTAMP TIMESTAMP,
  REC_UPDATE_USER_NAME STRING,
  REC_CREATE_DATE_KEY INTEGER,
  REC_CREATE_TIME_KEY INTEGER
) 
USING DELTA 
PARTITIONED BY (REC_CREATE_DATE_KEY) 
LOCATION 's3://skx-dataeng-datalake/consumption/agg_store_metrics_daily' 
TBLPROPERTIES ('layer' = 'GOLD')