-- Databricks notebook source
CREATE TABLE IF NOT EXISTS TRANSIENT_DL.LKP_SRC_TO_REF_HUB_STORE 
(
  SOURCE_SYSTEM_ID INTEGER,
  SOURCE_SYSTEM_NAME STRING,
  SOURCE_SYSTEM_NATURAL_KEY STRING,
  STORE_RHID INTEGER,
  STORE_GRPID STRING,
  PRIMARY_STORE_CURRENCY_RHID INTEGER,
  PRIMARY_STORE_CURRENCY_GRPID STRING,
  EFFECTIVE_START_TIMESTAMP TIMESTAMP,
  EFFECTIVE_END_TIMESTAMP TIMESTAMP,
  REC_CREATE_TIMESTAMP TIMESTAMP
) 
USING DELTA 
LOCATION 's3://test-dataeng-nonprod-datalake-staging/transient/datalake/integrated/lkp_src_to_ref_hub_store' 
TBLPROPERTIES ('layer' = 'SILVER');

-- COMMAND ----------

-- LKP HUB table for MST_STORE is loaded here for APROPOS Stores.
INSERT OVERWRITE TRANSIENT_DL.LKP_SRC_TO_REF_HUB_STORE
SELECT
  HUB_STORE.SOURCE_SYSTEM_ID,
  LKP_SRC_SYS_STORE.SOURCE_SYSTEM_NAME,
  HUB_STORE.SOURCE_SYSTEM_NATURAL_KEY,
  STORE.STORE_RHID,
  STORE.STORE_GRPID,
  STORE.PRIMARY_STORE_CURRENCY_RHID,
  STORE.PRIMARY_STORE_CURRENCY_GRPID,
  STORE.EFFECTIVE_START_TIMESTAMP,
  STORE.EFFECTIVE_END_TIMESTAMP,
  CURRENT_TIMESTAMP as REC_CREATE_TIMESTAMP
FROM
  REF_HUB.LKP_SRC_TO_REF_HUB HUB_STORE
  INNER JOIN REF_HUB.LKP_SOURCE_SYSTEM LKP_SRC_SYS_STORE 
  ON LKP_SRC_SYS_STORE.SOURCE_SYSTEM_ID = HUB_STORE.SOURCE_SYSTEM_ID
  INNER JOIN REF_HUB.MST_STORE STORE 
  ON HUB_STORE.GRPID = STORE.STORE_GRPID
WHERE
  HUB_STORE.REF_HUB_TABLE_NAME = 'MST_STORE'
  AND LKP_SRC_SYS_STORE.SOURCE_SYSTEM_NAME = 'APROPOS';

-- COMMAND ----------

select count(*) row_count from TRANSIENT_DL.LKP_SRC_TO_REF_HUB_STORE; 
-- 0

-- COMMAND ----------

CREATE TABLE IF NOT EXISTS TRANSIENT_DL.LKP_SRC_TO_REF_HUB_PRODUCT 
(
  SOURCE_SYSTEM_ID INTEGER,
  SOURCE_SYSTEM_NAME STRING,
  SOURCE_SYSTEM_NATURAL_KEY STRING,
  COLOR_RHID INTEGER,
  COLOR_GRPID STRING,
  PRODUCT_RHID INTEGER,
  PRODUCT_GRPID STRING,
  PRODUCT_LINE_RHID INTEGER,
  SIZE_RHID INTEGER,
  SIZE_GRPID STRING,
  STYLE_RHID INTEGER,
  STYLE_GRPID STRING,
  DIVISION_RHID INTEGER,
  DIVISION_GRPID STRING,
  EFFECTIVE_START_TIMESTAMP TIMESTAMP,
  EFFECTIVE_END_TIMESTAMP TIMESTAMP,
  REC_CREATE_TIMESTAMP TIMESTAMP
) 
USING DELTA
LOCATION 's3://test-dataeng-nonprod-datalake-staging/transient/datalake/integrated/lkp_src_to_ref_hub_product ' 
TBLPROPERTIES ('layer' = 'SILVER');

-- COMMAND ----------

-- INSERT INTO LKP HUB TABLE FOR MST_PRODUCT for all Products.

INSERT OVERWRITE  TRANSIENT_DL.LKP_SRC_TO_REF_HUB_PRODUCT 
SELECT
  HUB_PRODUCT.SOURCE_SYSTEM_ID,
  LKP_SRC_SYS_PRODUCT.SOURCE_SYSTEM_NAME,
  HUB_PRODUCT.SOURCE_SYSTEM_NATURAL_KEY,
  PRODUCT.COLOR_RHID,
  PRODUCT.COLOR_GRPID,
  PRODUCT.PRODUCT_RHID,
  PRODUCT.PRODUCT_GRPID,
  PRODUCT.PRODUCT_LINE_RHID,  
  PRODUCT.SIZE_RHID,
  PRODUCT.SIZE_GRPID,
  PRODUCT.STYLE_RHID,
  PRODUCT.STYLE_GRPID,
  PRODUCT.DIVISION_RHID,
  PRODUCT.DIVISION_GRPID,
  PRODUCT.EFFECTIVE_START_TIMESTAMP,
  PRODUCT.EFFECTIVE_END_TIMESTAMP,
  CURRENT_TIMESTAMP as REC_CREATE_TIMESTAMP
FROM
  REF_HUB.LKP_SRC_TO_REF_HUB HUB_PRODUCT
  INNER JOIN REF_HUB.LKP_SOURCE_SYSTEM LKP_SRC_SYS_PRODUCT 
  ON LKP_SRC_SYS_PRODUCT.SOURCE_SYSTEM_ID = HUB_PRODUCT.SOURCE_SYSTEM_ID
  INNER JOIN REF_HUB.MST_PRODUCT PRODUCT 
  ON HUB_PRODUCT.GRPID = PRODUCT.PRODUCT_GRPID
WHERE
  HUB_PRODUCT.REF_HUB_TABLE_NAME = 'MST_PRODUCT';

-- COMMAND ----------

select count(*) row_count from  TRANSIENT_DL.LKP_SRC_TO_REF_HUB_PRODUCT;
--0

-- COMMAND ----------

CREATE TABLE IF NOT EXISTS TRANSIENT_DL.APROPOS_SALES_BASE_DAILY
USING DELTA 
LOCATION 's3://skx-dataeng-nonprod-datalake-staging/transient/datalake/integrated/apropos_sales_base_daily' 
TBLPROPERTIES ('LAYER' = 'SILVER')
AS 
select * from 
BRZ_CURR_APROPOS_ATB.SALES SALES
WHERE SALES.REC_UPDATE_TIMESTAMP  > NVL(( SELECT MAX(SRC_LAST_UPD_TIMESTAMP) FROM DELTA_LOGS.USECASE_AUDIT_LOGS 
                                           WHERE JOBNAME='SJ3-SLV dtl_retail_sales_apropos' AND LOAD_STATUS = 'COMPLETED'),
                                        TO_DATE('1900-01-01','yyyy-MM-dd'));

-- COMMAND ----------

INSERT OVERWRITE TRANSIENT_DL.APROPOS_SALES_BASE_DAILY
select * from 
BRZ_CURR_APROPOS_ATB.SALES SALES
WHERE SALES.REC_UPDATE_TIMESTAMP  > NVL(( SELECT MAX(SRC_LAST_UPD_TIMESTAMP) FROM DELTA_LOGS.USECASE_AUDIT_LOGS 
                                    WHERE JOBNAME='SJ3-SLV dtl_retail_sales_apropos' AND LOAD_STATUS = 'COMPLETED'),
                                    TO_DATE('1900-01-01','yyyy-MM-dd'));

-- COMMAND ----------

select count(*) row_count from TRANSIENT_DL.APROPOS_SALES_BASE_DAILY;
--264392624

-- COMMAND ----------

INSERT INTO DELTA_LOGS.USECASE_AUDIT_LOGS 
SELECT 
'SJ3-SLV dtl_retail_sales_apropos',
MAX(REC_UPDATE_TIMESTAMP),
NULL, 
CURRENT_TIMESTAMP ,
'SJ3-SLV dtl_retail_sales_apropos', 
NULL,
NULL
FROM TRANSIENT_DL.APROPOS_SALES_BASE_DAILY ;

-- COMMAND ----------

CREATE TABLE IF NOT EXISTS TRANSIENT_DL.DLY_SALES_STORE 
(
  ORDER_ID INTEGER,
  ORDER_ITEM_ID INTEGER,
  ORDER_TIMESTAMP DATE,
  ORDER_DATE_KEY INTEGER,
  STORE_RHID INTEGER,
  STORE_GRPID STRING,
  PRIMARY_STORE_CURRENCY_RHID INTEGER,
  PRIMARY_STORE_CURRENCY_GRPID STRING,
  REC_CREATE_TIMESTAMP TIMESTAMP
) 
USING DELTA 
LOCATION 's3://test-dataeng-nonprod-datalake-staging/transient/datalake/integrated/dly_sales_store' 
TBLPROPERTIES ('layer' = 'SILVER');

-- COMMAND ----------

----This table will hold only STORE related fields for SALES with incremental data from the last run.

INSERT OVERWRITE TRANSIENT_DL.DLY_SALES_STORE
SELECT
  SALES.SL_INV_NUM AS ORDER_ID,
  SALES.SL_TRAN AS ORDER_ITEM_ID,
  TO_UTC_TIMESTAMP(
  CASE
   WHEN SUBSTR(SL_TIME,7,2) = 'pm' THEN CAST(SL_DATE ||' '|| CAST(CAST(SUBSTR(SL_TIME,1,2) AS INT) + 12 AS STRING)|| SUBSTR(SL_TIME,3,3) || ':00' 
   AS TIMESTAMP)
   WHEN SUBSTR(SL_TIME, 7, 2) = 'am' THEN CAST(SL_DATE || ' ' || SUBSTR(SL_TIME, 1, 2) || SUBSTR(SL_TIME, 3, 3) || ':00' AS TIMESTAMP ) 
   END 
   , "PST") AS ORDER_TIME_STAMP,
  CAST(DATE_FORMAT(SALES.SL_DATE, 'yyyyMMdd') AS INT) AS ORDER_DATE_KEY,
  HUB_SALES_STORE.STORE_RHID,
  HUB_SALES_STORE.STORE_GRPID,
  HUB_SALES_STORE.PRIMARY_STORE_CURRENCY_RHID,
  HUB_SALES_STORE.PRIMARY_STORE_CURRENCY_GRPID,
  CURRENT_TIMESTAMP AS REC_CREATE_TIMESTAMP
FROM
  TRANSIENT_DL.APROPOS_SALES_BASE_DAILY SALES
  LEFT OUTER JOIN TRANSIENT_DL.LKP_SRC_TO_REF_HUB_STORE HUB_SALES_STORE 
  ON SALES.SL_STORE || '_' || HUB_SALES_STORE.SOURCE_SYSTEM_ID = HUB_SALES_STORE.SOURCE_SYSTEM_NATURAL_KEY
  AND SALES.SL_DATE BETWEEN HUB_SALES_STORE.EFFECTIVE_START_TIMESTAMP AND HUB_SALES_STORE.EFFECTIVE_END_TIMESTAMP;

-- COMMAND ----------

select count(*) row_count from TRANSIENT_DL.DLY_SALES_STORE;
--264392624

-- COMMAND ----------

CREATE TABLE IF NOT EXISTS TRANSIENT_DL.DLY_SALES_PRODUCT
(
  ORDER_ID INTEGER,
  ORDER_ITEM_ID INTEGER,
  ORDER_STATUS_CODE STRING,
  ORDER_CHANNEL_CODE STRING,
  TRANSACTION_TYPE_CODE STRING,
  ORDER_TIMESTAMP TIMESTAMP,
  ORDER_DATE_KEY INTEGER,
  COLOR_RHID INTEGER,
  COLOR_GRPID STRING,
  STORE_RHID STRING,
  PRODUCT_RHID INTEGER,
  PRODUCT_GRPID STRING,
  SIZE_RHID INTEGER,
  SIZE_GRPID STRING,
  STYLE_RHID INTEGER,
  STYLE_GRPID STRING,
  DIVISION_RHID INTEGER,
  DIVISION_GRPID STRING,
  CATALOG_ITEM_CODE STRING,
  SHIP_STORE_RHID INTEGER,
  SHIP_STORE_GRPID STRING,
  ITEM_TYPE_DESC STRING,
  UNIT_PRICE_AMT DECIMAL(20, 6),
  SALES_QTY INTEGER,
  TAX_TYPE1_CODE STRING,
  TAX_TYPE1_AMT DECIMAL(20, 6),
  TAX_TYPE2_CODE STRING,
  TAX_TYPE2_AMT DECIMAL(20, 6),
  TAX_TYPE3_CODE STRING,
  TAX_TYPE3_AMT DECIMAL(20, 6),
  TAX_TYPE4_CODE STRING,
  TAX_TYPE4_AMT DECIMAL(20, 6),
  DISCOUNT1_REASON_CODE STRING,
  CANCEL_DATE DATE,
  RETURN_DATE DATE,
  VERSION_NBR INTEGER,
  CARRIER_NAME STRING,
  SHIPPING_VENDOR_NAME STRING,
  TRACKING_CODE STRING,
  CHARGE_IND INTEGER,
  PICK_CODE STRING,
  AVAILABLE_DATE DATE,
  PICK_DATE DATE,
  EMAIL_NOTIFIED_IND INTEGER,
  ORDER_FAILED_NOTIFIED_IND INTEGER,
  ORDER_FAILED_NOTIFIED_DATE DATE,
  ORDER_NOTES_TEXT STRING,
  REVIEW_NOTIFIED_IND INTEGER,
  CREDITED_IND INTEGER,
  COMMENTS_TEXT STRING,
  SHIPPING_METHOD_CODE STRING,
  SHIP_DATE DATE,
  CHARGE_TIMESTAMP TIMESTAMP,
  REC_CREATE_TIMESTAMP TIMESTAMP
) 
USING DELTA 
LOCATION 's3://test-dataeng-nonprod-datalake-staging/transient/datalake/integrated/dly_sales_product' 
TBLPROPERTIES ('layer' = 'SILVER');

-- COMMAND ----------

----This table will hold only PRODUCT related fields for SALES with incremental data from the last run.

INSERT OVERWRITE TRANSIENT_DL.DLY_SALES_PRODUCT
SELECT
  DISTINCT 
  SALES.SL_INV_NUM AS ORDER_ID,
  SALES.SL_TRAN AS ORDER_ITEM_ID,
  NULL AS ORDER_STATUS_CODE,
  'RETAIL' AS ORDER_CHANNEL_CODE,
  SALES.SL_TRANTYPE AS TRANSACTION_TYPE_CODE,
  TO_UTC_TIMESTAMP(
  CASE
   WHEN SUBSTR(SL_TIME,7,2) = 'pm' THEN CAST(SL_DATE ||' '|| CAST(CAST(SUBSTR(SL_TIME,1,2) AS INT) + 12 AS STRING)|| SUBSTR(SL_TIME,3,3) || ':00' 
   AS TIMESTAMP)
   WHEN SUBSTR(SL_TIME, 7, 2) = 'am' THEN CAST(SL_DATE || ' ' || SUBSTR(SL_TIME, 1, 2) || SUBSTR(SL_TIME, 3, 3) || ':00' AS TIMESTAMP ) 
   END 
   , "PST") AS ORDER_TIME_STAMP,
  CAST(DATE_FORMAT(SALES.SL_DATE, 'yyyyMMdd') AS INT) AS ORDER_DATE_KEY,
  HUB_SALES_PRODUCT.COLOR_RHID,
  HUB_SALES_PRODUCT.COLOR_GRPID,
  DLY_SALES_STORE.STORE_RHID,
  HUB_SALES_PRODUCT.PRODUCT_RHID,
  HUB_SALES_PRODUCT.PRODUCT_GRPID,
  HUB_SALES_PRODUCT.SIZE_RHID,
  HUB_SALES_PRODUCT.SIZE_GRPID,
  HUB_SALES_PRODUCT.STYLE_RHID,
  HUB_SALES_PRODUCT.STYLE_GRPID,
  HUB_SALES_PRODUCT.DIVISION_RHID,
  HUB_SALES_PRODUCT.DIVISION_GRPID,
  SALES.SL_EITEM AS CATALOG_ITEM_CODE,
  NULL AS SHIP_STORE_RHID,
  NULL AS SHIP_STORE_GRPID,
  NULL AS ITEM_TYPE_DESC,
  SALES.SL_PRICE AS UNIT_PRICE_AMT,
  SALES.SL_QTY AS SALES_QTY,
  SALES.SL_TAXMODE AS TAX_TYPE1_CODE,
  SALES.SL_TAXAMT1 AS TAX_TYPE1_AMT,
  NULL AS TAX_TYPE2_CODE,
  SALES.SL_TAXAMT2 AS TAX_TYPE2_AMT,
  NULL AS TAX_TYPE3_CODE,
  SALES.SL_TAXAMT3 AS TAX_TYPE3_AMT,
  NULL AS TAX_TYPE4_CODE,
  SALES.SL_TAXAMT4 AS TAX_TYPE4_AMT,  
  SALES.SL_DISREASON AS DISCOUNT1_REASON_CODE,
  CAST(NULL AS DATE) AS CANCEL_DATE,
  CAST(NULL AS DATE) AS RETURN_DATE,
  NULL AS VERSION_NBR,
  NULL AS CARRIER_NAME,
  NULL AS SHIPPING_VENDOR_NAME,
  NULL AS TRACKING_CODE,
  NULL AS CHARGE_IND,
  NULL AS PICK_CODE,
  CAST(NULL AS DATE) AS AVAILABLE_DATE,
  CAST(NULL AS DATE)  AS PICK_DATE,
  NULL AS EMAIL_NOTIFIED_IND,
  NULL AS ORDER_FAILED_NOTIFIED_IND,
  CAST(NULL AS DATE) AS ORDER_FAILED_NOTIFIED_DATE,
  NULL AS ORDER_NOTES_TEXT,
  NULL AS REVIEW_NOTIFIED_IND,
  NULL AS CREDITED_IND,
  NULL AS COMMENTS_TEXT,
  NULL AS SHIPPING_METHOD_CODE,
  CAST(NULL AS DATE) AS SHIP_DATE,
  CAST(NULL AS TIMESTAMP) AS CHARGE_TIMESTAMP,
  CURRENT_TIMESTAMP AS REC_CREATE_TIMESTAMP
FROM
  TRANSIENT_DL.APROPOS_SALES_BASE_DAILY SALES
  LEFT OUTER JOIN BRZ_CURR_APROPOS_ATB.UPCREF 
  ON SALES.SL_SEQ = UPCREF.UP_SEQ
  AND SALES.SL_SIZE_ID = UPCREF.UP_SIZE
  LEFT OUTER JOIN TRANSIENT_DL.LKP_SRC_TO_REF_HUB_PRODUCT HUB_SALES_PRODUCT 
  ON UPCREF.UP_CODE || '_' ||   HUB_SALES_PRODUCT.SOURCE_SYSTEM_ID = HUB_SALES_PRODUCT.SOURCE_SYSTEM_NATURAL_KEY
  AND HUB_SALES_PRODUCT.SOURCE_SYSTEM_NAME = 'APROPOS'
  AND SALES.SL_DATE BETWEEN HUB_SALES_PRODUCT.EFFECTIVE_START_TIMESTAMP AND HUB_SALES_PRODUCT.EFFECTIVE_END_TIMESTAMP
  LEFT OUTER JOIN TRANSIENT_DL.DLY_SALES_STORE DLY_SALES_STORE
  ON  SALES.SL_INV_NUM = DLY_SALES_STORE.ORDER_ID
  AND SALES.SL_TRAN = DLY_SALES_STORE.ORDER_ITEM_ID
  AND CAST(DATE_FORMAT(SALES.SL_DATE, 'yyyyMMdd') AS INT) = DLY_SALES_STORE.ORDER_DATE_KEY;

-- COMMAND ----------

select count(*) row_count from TRANSIENT_DL.DLY_SALES_PRODUCT;
--264392551

-- COMMAND ----------

CREATE TABLE IF NOT EXISTS TRANSIENT_DL.DLY_SALES 
(
  ORDER_ID INTEGER,
  ORDER_ITEM_ID INTEGER,
  ORDER_STATUS_CODE STRING,
  ORDER_CHANNEL_CODE STRING,
  TRANSACTION_TYPE_CODE STRING,
  ORDER_TIMESTAMP TIMESTAMP,
  ORDER_DATE_KEY INTEGER,
  COLOR_RHID INTEGER,
  COLOR_GRPID STRING,
  PRODUCT_RHID INTEGER,
  PRODUCT_GRPID STRING,
  SIZE_RHID INTEGER,
  SIZE_GRPID STRING,
  STYLE_RHID INTEGER,
  STYLE_GRPID STRING,
  DIVISION_RHID INTEGER,
  DIVISION_GRPID STRING,
  CATALOG_ITEM_CODE STRING,
  STORE_RHID INTEGER,
  STORE_GRPID STRING,
  SHIP_STORE_RHID INTEGER,
  SHIP_STORE_GRPID STRING,
  ITEM_TYPE_DESC STRING,
  UNIT_PRICE_AMT DECIMAL(20, 6),
  SALES_QTY INTEGER,
  TAX_TYPE1_CODE STRING,
  TAX_TYPE1_AMT DECIMAL(20, 6),
  TAX_TYPE2_CODE STRING,
  TAX_TYPE2_AMT DECIMAL(20, 6),
  TAX_TYPE3_CODE STRING,
  TAX_TYPE3_AMT DECIMAL(20, 6),
  TAX_TYPE4_CODE STRING,
  TAX_TYPE4_AMT DECIMAL(20, 6),
  DISCOUNT1_REASON_CODE STRING,
  CANCEL_DATE DATE,
  RETURN_DATE DATE,
  VERSION_NBR INTEGER,
  CARRIER_NAME STRING,
  SHIPPING_VENDOR_NAME STRING,
  TRACKING_CODE STRING,
  CHARGE_IND INTEGER,
  PICK_CODE STRING,
  AVAILABLE_DATE DATE,
  PICK_DATE DATE,
  EMAIL_NOTIFIED_IND INTEGER,
  ORDER_FAILED_NOTIFIED_IND INTEGER,
  ORDER_FAILED_NOTIFIED_DATE DATE,
  ORDER_NOTES_TEXT STRING,
  REVIEW_NOTIFIED_IND INTEGER,
  CREDITED_IND INTEGER,
  COMMENTS_TEXT STRING,
  SHIPPING_METHOD_CODE STRING,
  SHIP_DATE DATE,
  CHARGE_TIMESTAMP TIMESTAMP,
  CURRENCY_RHID INTEGER,
  CURRENCY_GRPID STRING,
  REC_CREATE_TIMESTAMP TIMESTAMP
) 
USING DELTA 
LOCATION 's3://test-dataeng-nonprod-datalake-staging/transient/datalake/integrated/dly_sales' 
TBLPROPERTIES ('layer' = 'SILVER');

-- COMMAND ----------

--- This table will bring together all attributes from STORE and PRODUCT universe for SALES to match final table structure: DTL_RETAIL_SALES 

INSERT OVERWRITE TRANSIENT_DL.DLY_SALES
SELECT
  DISTINCT 
  DLY_SALES_PRODUCT.ORDER_ID,
  DLY_SALES_PRODUCT.ORDER_ITEM_ID,
  DLY_SALES_PRODUCT.ORDER_STATUS_CODE,
  DLY_SALES_PRODUCT.ORDER_CHANNEL_CODE,
  DLY_SALES_PRODUCT.TRANSACTION_TYPE_CODE,
  DLY_SALES_PRODUCT.ORDER_TIMESTAMP,
  DLY_SALES_PRODUCT.ORDER_DATE_KEY,   
  DLY_SALES_PRODUCT.COLOR_RHID,
  DLY_SALES_PRODUCT.COLOR_GRPID,
  DLY_SALES_PRODUCT.PRODUCT_RHID,
  DLY_SALES_PRODUCT.PRODUCT_GRPID,
  DLY_SALES_PRODUCT.SIZE_RHID,
  DLY_SALES_PRODUCT.SIZE_GRPID,
  DLY_SALES_PRODUCT.STYLE_RHID,
  DLY_SALES_PRODUCT.STYLE_GRPID,
  DLY_SALES_PRODUCT.DIVISION_RHID,
  DLY_SALES_PRODUCT.DIVISION_GRPID,
  DLY_SALES_PRODUCT.CATALOG_ITEM_CODE,
  DLY_SALES_STORE.STORE_RHID,
  DLY_SALES_STORE.STORE_GRPID,
  DLY_SALES_PRODUCT.SHIP_STORE_RHID,
  DLY_SALES_PRODUCT.SHIP_STORE_GRPID,
  DLY_SALES_PRODUCT.ITEM_TYPE_DESC,
  DLY_SALES_PRODUCT.UNIT_PRICE_AMT,
  DLY_SALES_PRODUCT.SALES_QTY,  
  DLY_SALES_PRODUCT.TAX_TYPE1_CODE,
  DLY_SALES_PRODUCT.TAX_TYPE1_AMT,
  DLY_SALES_PRODUCT.TAX_TYPE2_CODE,
  DLY_SALES_PRODUCT.TAX_TYPE2_AMT,
  DLY_SALES_PRODUCT.TAX_TYPE3_CODE,
  DLY_SALES_PRODUCT.TAX_TYPE3_AMT,
  DLY_SALES_PRODUCT.TAX_TYPE4_CODE,
  DLY_SALES_PRODUCT.TAX_TYPE4_AMT,  
  DLY_SALES_PRODUCT.DISCOUNT1_REASON_CODE,
  DLY_SALES_PRODUCT.CANCEL_DATE,
  DLY_SALES_PRODUCT.RETURN_DATE,
  DLY_SALES_PRODUCT.VERSION_NBR,
  DLY_SALES_PRODUCT.CARRIER_NAME,
  DLY_SALES_PRODUCT.SHIPPING_VENDOR_NAME,
  DLY_SALES_PRODUCT.TRACKING_CODE,
  DLY_SALES_PRODUCT.CHARGE_IND,
  DLY_SALES_PRODUCT.PICK_CODE,
  DLY_SALES_PRODUCT.AVAILABLE_DATE,
  DLY_SALES_PRODUCT.PICK_DATE,
  DLY_SALES_PRODUCT.EMAIL_NOTIFIED_IND,
  DLY_SALES_PRODUCT.ORDER_FAILED_NOTIFIED_IND,
  DLY_SALES_PRODUCT.ORDER_FAILED_NOTIFIED_DATE,
  DLY_SALES_PRODUCT.ORDER_NOTES_TEXT,
  DLY_SALES_PRODUCT.REVIEW_NOTIFIED_IND,
  DLY_SALES_PRODUCT.CREDITED_IND,
  DLY_SALES_PRODUCT.COMMENTS_TEXT,
  DLY_SALES_PRODUCT.SHIPPING_METHOD_CODE,
  DLY_SALES_PRODUCT.SHIP_DATE,
  DLY_SALES_PRODUCT.CHARGE_TIMESTAMP,
  DLY_SALES_STORE.PRIMARY_STORE_CURRENCY_RHID AS CURRENCY_RHID,
  DLY_SALES_STORE.PRIMARY_STORE_CURRENCY_GRPID AS CURRENCY_GRPID,  
  DLY_SALES_PRODUCT.REC_CREATE_TIMESTAMP
FROM
  TRANSIENT_DL.DLY_SALES_PRODUCT DLY_SALES_PRODUCT
  INNER JOIN TRANSIENT_DL.DLY_SALES_STORE DLY_SALES_STORE 
  ON DLY_SALES_PRODUCT.ORDER_ID = DLY_SALES_STORE.ORDER_ID 
  AND DLY_SALES_PRODUCT.ORDER_ITEM_ID = DLY_SALES_STORE.ORDER_ITEM_ID 
  AND NVL(DLY_SALES_PRODUCT.STORE_RHID,'*') = NVL(DLY_SALES_STORE.STORE_RHID,'*')
  AND DLY_SALES_PRODUCT.ORDER_DATE_KEY = DLY_SALES_STORE.ORDER_DATE_KEY;

-- COMMAND ----------

select count(*) row_count from TRANSIENT_DL.DLY_SALES;
--264392551

-- COMMAND ----------

-- INSERT APROPOS:SALES INTO FINAL TABLE : SLV_RETAIL_SALES.DTL_RETAIL_SALES
INSERT INTO
  SLV_RETAIL_SALES.DTL_RETAIL_SALES
SELECT
  DISTINCT
  ORDER_ID,
  ORDER_ITEM_ID,
  ORDER_STATUS_CODE,
  ORDER_CHANNEL_CODE,
  TRANSACTION_TYPE_CODE,
  ORDER_TIMESTAMP,
  ORDER_DATE_KEY,
  COLOR_RHID,
  COLOR_GRPID,
  PRODUCT_RHID,
  PRODUCT_GRPID,
  SIZE_RHID,
  SIZE_GRPID,
  STYLE_RHID,
  STYLE_GRPID,
  DIVISION_RHID,
  DIVISION_GRPID,
  CATALOG_ITEM_CODE,
  STORE_RHID,
  STORE_GRPID,
  SHIP_STORE_RHID,
  SHIP_STORE_GRPID,
  ITEM_TYPE_DESC,
  UNIT_PRICE_AMT,
  SALES_QTY,
  TAX_TYPE1_CODE,
  TAX_TYPE1_AMT,
  TAX_TYPE2_CODE,
  TAX_TYPE2_AMT,
  TAX_TYPE3_CODE,
  TAX_TYPE3_AMT,
  TAX_TYPE4_CODE,
  TAX_TYPE4_AMT,
  DISCOUNT1_REASON_CODE,
  CANCEL_DATE,
  RETURN_DATE,
  VERSION_NBR,
  CARRIER_NAME,
  SHIPPING_VENDOR_NAME,
  TRACKING_CODE,
  CHARGE_IND,
  PICK_CODE,
  AVAILABLE_DATE,
  PICK_DATE,
  EMAIL_NOTIFIED_IND,
  ORDER_FAILED_NOTIFIED_IND,
  ORDER_FAILED_NOTIFIED_DATE,
  ORDER_NOTES_TEXT,
  REVIEW_NOTIFIED_IND,
  CREDITED_IND,
  COMMENTS_TEXT,
  SHIPPING_METHOD_CODE,
  SHIP_DATE,
  CHARGE_TIMESTAMP,
  CURRENCY_RHID,
  CURRENCY_GRPID,
  CURRENT_TIMESTAMP AS REC_CREATE_TIMESTAMP,
  'DL_JOB_NAME' REC_CREATE_USER_NAME,
  CURRENT_TIMESTAMP REC_UPDATE_TIMESTAMP,
  'DL_JOB_NAME' REC_UPDATE_USER_NAME,
  DATE_FORMAT(CURRENT_TIMESTAMP, 'yyyyMMdd') REC_CREATE_DATE_KEY,
  DATE_FORMAT(CURRENT_TIMESTAMP, 'HHmm') REC_CREATE_TIME_KEY
FROM
  TRANSIENT_DL.DLY_SALES DLY_SALES;

-- COMMAND ----------

UPDATE DELTA_LOGS.USECASE_AUDIT_LOGS
SET LOAD_STATUS = 'COMPLETED' , 
REC_UPDATE_TIMESTAMP = CURRENT_TIMESTAMP,
REC_UPDATE_USER_NAME = 'SJ3-SLV dtl_retail_sales_apropos'
WHERE JOBNAME = 'SJ3-SLV dtl_retail_sales_apropos'
AND REC_CREATE_TIMESTAMP = ( SELECT MAX(REC_CREATE_TIMESTAMP) FROM DELTA_LOGS.USECASE_AUDIT_LOGS 
                              WHERE JOBNAME = 'SJ3-SLV dtl_retail_sales_apropos' AND LOAD_STATUS IS NULL)
AND LOAD_STATUS IS NULL;

-- COMMAND ----------

--Input count
select count(*) row_count from TRANSIENT_DL.APROPOS_SALES_BASE_DAILY;

-- COMMAND ----------

--- Output count
SELECT count(*) row_count FROM SLV_RETAIL_SALES.DTL_RETAIL_SALES --36010
WHERE REC_UPDATE_TIMESTAMP = (SELECT max(REC_UPDATE_TIMESTAMP) FROM SLV_RETAIL_SALES.DTL_RETAIL_SALES WHERE  ORDER_CHANNEL_CODE ='RETAIL')  
AND ORDER_CHANNEL_CODE ='RETAIL' 
AND REC_UPDATE_TIMESTAMP > (SELECT MAX(REC_CREATE_TIMESTAMP) FROM DELTA_LOGS.USECASE_AUDIT_LOGS 
                              WHERE JOBNAME = 'SJ3-SLV dtl_retail_sales_apropos' AND LOAD_STATUS IS NOT NULL ) ;
